---
title: "IBM Data Engineering Professional Certificate"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
    css: style.css
---

## Data Engineering Course

Coursework for the IBM Data Engineering Professional Certificate

* Introduction to Data Engineering
  - Theoretical Foundations underlying the discipline of Data Engineering
  
* Python for Data Science, AI & Development
  - Introduction to Python for Numerical Programming
  - Core Functionality, Programming Control Statements, Numpy and Pandas
* [Python-Project-for-Data-Engineering/index.html](Python Project for Data Engineering)
  - Extract Transform and Load (ETL) data using an IDE 
  - More Advanced Python Programming
  
* Introduction to Relational Databases (RDBMS)
* Databases and SQL for Data Science with Python
* Hands-on Introduction to Linux Commands and Shell Scripting
* [Getting Started with Data Warehousing and BI Analytics](Getting-started-with-Data-warehousing-and-BI-Analytics/index.html)
* Introduction to NoSQL Databases
* Introduction to Big Data with Spark and Hadoop
* Data Engineering Capstone Project
